### ISSUE TITLE
Would you like to provide the script for generate the saliency_map, inpainted_1x, inpainted_1d5x

### ISSUE THREAD

**Issue by trouble-maker007** [posterllava/PosterLLaVA#3]
use the similar method to get the saliency map and inpainted result:
https://github.com/CyberAgentAILab/RALF/tree/c51db6032acbd0bd0ce72433becce08317e7874d?tab=readme-ov-file#pre-processing-dataset

and what is the difference between the inpainted_1x and inpainted_1d5x

**Comment by posterllava** [comment]
We randomly inpainted 0.5x additional areas (other than the ground-truth box areas) to get the "inpainted_1d5x" and use it as the training set. This is to avoid over-fitting cause inpainting is not perfect (always leave some unwanted 'clue' for model). The 'inpainted_1x' is inpainted normally and used as the evaluation set.

The inpainted background image and saliency map will some be released, too.

**Comment by trouble-maker007** [comment]
@posterllava thanks, got it

**Comment by zimenglan-sysu-512** [comment]
any update？will release the tools and scripts that generate the inpainted results?

**Comment by posterllava** [comment]
> any update？will release the tools and scripts that generate the inpainted results?

We here mention again the methods used for inpainting and saliency detection in our paper, which are lama [https://github.com/saic-mdal/lama ](https://github.com/posterllava/PosterLLaVA/issues/URL)and basenet [https://github.com/xuebinqin/BASNet](https://github.com/posterllava/PosterLLaVA/issues/url).

Hope the official script can solve your problem!
