### ISSUE TITLE
zero3_offload.json

### ISSUE THREAD

**Issue by lgs00** [posterllava/PosterLLaVA#9]
May I ask about the setting of zero3_offload.
could you give zero3_offload.json.

**Comment by KeyaoZhao** [comment]
> May I ask about the setting of zero3_offload. could you give zero3_offload.json.

Hello, I also met this problem. How do you solve it? What's the content of 'zero3_offload.json'? Thanks a lot.

**Comment by KeyaoZhao** [comment]
> > May I ask about the setting of zero3_offload. could you give zero3_offload.json.
> 
> Hello, I also met this problem. How do you solve it? What's the content of 'zero3_offload.json'? Thanks a lot.

Solved. Thanks~

**Comment by posterllava** [comment]
Uploaded. zero3_offload is an optional DeepSpeed script for training acceleration. You can find it now in PosterLLaVa/llava/scripts.
